### ISSUE TITLE
Community Grants Program

### ISSUE THREAD

**Issue by joecartesi** [cartesi/cips#35]
**Cartesi Community Grants Program**

**Summary**

We propose to start a community-driven Cartesi Grants Program to fund public goods and reusable open-source projects that drive value to the Cartesi ecosystem through community-led development and adoption of the Cartesi technology.

Our proposal is inspired by grant pilot programs that have been previously rolled out by [Compound](https://www.comp.xyz/t/compound-grants-program/1292), [Uniswap](https://gov.uniswap.org/t/rfc-uniswap-grants-program-v0-1/9081), and [Aave](https://governance.aave.com/t/arc-aave-community-grants-program/3642).

This initiative is meant to be a simple MVP of a Cartesi Grants Program. If successful, it is our hope that this program will be renewed, refined, and further decentralized over time, with the goal of eventually becoming a fully fledged Cartesi Grants DAO.

**Budget and Duration**

The proposal recommends a maximum funding cap of $250,000 per quarter, with an initial program duration of two quarters.  

If this proposal passes, funding will be denominated in stablecoins from the Cartesi Foundation’s community treasury, deposited in a Cartesi Grants Program multi-sig wallet to be made public upon program funding.

Upon conclusion of the program duration, any amounts remaining in the multi-sig will be returned to the Cartesi Foundation treasury unless a proposal to extend the Grants Program has been implemented.  

**Grant Council**

Grant administration is inherently subjective and, in many cases, requires specialized knowledge to assess the technological viability of applications and ensure that payment milestones are being met. 

Given these realities, we propose establishing a Grant Council that has the power to review and administer grants on a discretionary basis, with community ratification sought for grants above a certain funding threshold (as explained further below).

The purpose of the initial Grant Council is to test the hypothesis that a Cartesi Grants Program can prove to be an effective means of delivering value to the Cartesi ecosystem before scaling the program.

**Grant Council Members:**

* Erick de Moura: Co-Founder & Core Contributor

* Colin Steil: Co-Founder & Core Contributor

* Milton Jonathan: Head of Product

* Felipe Argento: Core Blockchain Developer

* Carlo Fragni: Solution Architect Lead

* Gabriel Barros: Developer Advocate

The Grant Council will function as a 4 of 7 multi-sig.

In addition, a Grants Program Manager will be appointed to facilitate the proposal process and manage the program.

Grants Program Manager:

* Joe Nance: Director of Cartesi Labs

**Process and Timeline**

If approved, the MVP will begin upon funding of the multi-sig and run for a period of six months.  Grant applications will be accepted on a rolling basis for the duration of the program.  The Grant Council will stop accepting applications two weeks before the end of the MVP Grant Program, in order to evaluate any remaining applications.

A detailed application process will be shared shortly after this proposal passes. In general, Grant Council members will review each application and evaluate its potential value to the Cartesi ecosystem.

Grant applications in the MVP program will follow one of two “tracks” depending on the size of the request:

* Rapid Grants ($5,000 USD or less)
    * Applications reviewed by Grant Council only
    * Funding decisions made in Grant Council’s sole discretion
    * Grant Council to publicly announce details of successfully funded rapid grants on Cartesi Discourse Governance Forum
* Community Grants (greater than $5,000 USD)
    * Applications posted publicly to the Cartesi Discourse Governance Forum (link to be shared shortly after this proposal passes)
    * Grant Council conducts review for consistency with Grant Program mandate (explained in further detail below), ecosystem impact, and technological feasibility, which will be deliberated openly in a read-only channel found in Cartesi’s Discord.
        * The Grant Council’s review may include private interviews with grant applicants, the contents of which will be publicly disclosed to the extent necessary to provide insight into the Council’s decision to approve or deny the application
    * Applications that pass Grant Council review will be transferred to Snapshot for community vote
        * Grant Council will provide justification in the Cartesi Discourse Governance Forum for any community grant applications that are not elevated to a Snapshot vote
    * Applications receiving community approval on Snapshot will be funded by the Grant Council (except under exceptional circumstances)
        * Any deviations from the Snapshot vote by the Grant Council must be fully and publicly explained in the Cartesi Discourse Governance Forum  

At the end of the MVP program (after all milestone payments are made), the multi-sig holders will ensure that any unspent funds are returned to the community treasury for use at a later time.

**Applicant Project Guidelines**

The Cartesi Community Grants Program is dedicated to funding projects that promote the sustainable growth of the Cartesi ecosystem, with a primary focus on public goods projects, reusable infrastructure, and reusable DApp components.

Examples of the projects falling under the Community Grants Program’s mandate include:

* A DAO governance tool running on Cartesi technology
* An order book that can be integrated into DeFi applications running on Cartesi technology
* Tooling and convenience layers (such as DApp development frameworks)
* An aggregator or sequencer for Cartesi Rollups
* Open-source front ends (such as a wallet UI)

Examples of the types of projects that would likely fall outside of the Community Grants Program’s mandate include:

* Full scale development of a DApp that implements a profit model (note that open-source back-end logic for such DApps may properly fall within the Grants Program’s mandate depending on ecosystem impact and reusability)
* A branded or closed-source front-end
* DApps that do not require Cartesi technology to run or could be better implemented without it 	

We recognize that some decisions regarding which applications fall within the Grants Program mandate may be subjective in nature.  The Grant Council will provide a full and public explanation for any grant applications that are rejected for falling outside of the Grants Program mandate.  

**Conclusion**

We feel that these program parameters are appropriate for a Cartesi Community Grants Program MVP.  This program is meant to be an experiment.  Upon the MVPs conclusion, it is our hope that the programs successes and shortcomings will be the subject of community review and feedback and that the Cartesi Community Grants Program will be renewed and iterated upon over time.

**Comment by colinsteil** [comment]
Fully onboard and looking forward to any comments on this. Very excited for the launch and further decentralization of Cartesi's grants program.

**Comment by brandonisaacson** [comment]
I'll be very excited to see this project in action.  Looking forward to this and other initiatives in decentralized governance for the Cartesi ecosystem.

**Comment by erickmoura** [comment]
I will be brimming with excitement to witness a thriving community of projects and grantees developing from here!!

**Comment by bmaia-cartesi** [comment]
Letting the community have an active voice brings Cartesi´s decentralization efforts one step further. I´m excited to see what builders will propose to make more in Web 3.0 with Cartesi tech. Im fully on board with this initiative

**Comment by dcharlesDZL** [comment]
Looking forward to the community appearing more about Cartesi rollup projects.

**Comment by packetstracer** [comment]
This looks good to us, in fact we thinks is a solid proposal because of the following.

- grant programs for software development help flourish interesting projects in the ecosystem
- decentralization and community involvement is a good thing to promote project ownership by holders
- the council member is a proven way to manage the selection and tracking of the projects
- a limited program time is also nice to test and improve any issues on the program

In brief it's a solid starting point in our opinion, but would like to point a matter about point 2 (decentralization and community driven selection).

Though we think decision making decentralization is important, we would like to raise the issue that selecting technological projects in a quite technological environment such as blockchain is, requires at least good knowledge of the technologies involved as well as software development to be able to score and prioritize projects:

- that are viable and can fit into the market
- that are within a fair price range
- where team members are capable of delivering the project

That's why we think the council is very important to ensure the health of the program and avoid the raise of "false" proposals, community and bot driven voting, and non appropriate project selection because of not adequate
knowledge.

So we think that keeping the council and not going to a full decentralization is important. We believe that some tasks like filtering projects should always still be done by a council. Other projects include the selection of the council by the community, with some constraints involved like max time a council member can stay in the council, member rotation number and time windows, etc.

Anyway, for this first program phase this is not a problem, but just wanted to point it out for future stages.

**Comment by DurableNetwork** [comment]
This looks very promising! It will strengthen the bond with builders and should give birth to inspiring new projects 👍

**Comment by calvinzhou-rockx** [comment]
Cannot wait to see what kind of innovative applications will show up!

**Comment by emanuelconunaemme** [comment]
This looks amazing! Would it make sense to add infra improvements as category? Improving the validators software and tooling can be beneficial for the community.
